apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: taskmanager-learning
spec:
  selector:
    app: task-service
  ports:
    - port: 3002
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: taskmanager-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: learning-task-service:k8s-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGODB_URI
              value: mongodb://mongo:27017
            - name: MONGODB_DATABASE
              value: taskmanager_learning
