apiVersion: v1
kind: Service
metadata:
  name: web-gateway
  namespace: taskmanager-learning
spec:
  selector:
    app: web-gateway
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
  namespace: taskmanager-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
        - name: web-gateway
          image: learning-web-gateway:k8s-v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: TASK_SERVICE_URL
              value: http://task-service:3002
